### ISSUE TITLE
nextpnr Pair Generation fails

### ISSUE THREAD

**Issue by TaoBi22** [FPGA-Research-Manchester/FABulous#32]
Looks like pair generation fails due to a change in the IO tiles used in fabric.csv - running the pair generation flow throws the error:

```
Traceback (most recent call last):
  File "/home/bea/Documents/KilburnSummer/FABulous/fabric_generator/fabric_gen.py", line 6207, in <module>
    npnrModel = genNextpnrModel(fabricObject)
  File "/home/bea/Documents/KilburnSummer/FABulous/fabric_generator/fabric_gen.py", line 4780, in genNextpnrModel
    for outPip in tile.pipMuxes_MapSourceToSinks[prefix + "O" + str(i)]:
KeyError: 'RAM2FAB_D0_O0'
```

This also wasn't picked up by CI, which I think is an issue with propagating the return code from the Python call through out of the Bash script that gets run - this is documented in #31.

**Comment by TaoBi22** [comment]
As it turns out this is nothing to do with the Python implementation and simply an issue in the run_fab_flow_nextpnr_pair.sh script! The non-default flow scripts hadn't been updated to operate on the new generic architecture tiles, but this is fixed in #34.
